version: '2'
services:
  web:
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
